#
# Phalcon Application Core
#

# Pull base image
FROM debian:8

MAINTAINER Serghei Iakovlev <serghei@phalconphp.com>

RUN mkdir -p /var/www/phalcon
WORKDIR /var/www/phalcon

# Set up the application directory
VOLUME ["/var/www/phalcon"]
